version: 1

suites:
  suite_name_1:
    concurrency:
      max_workers: 6
    package: example
    groups:
      group1:
        disable: False
        granularity: module
        modules: [test_module1, test_module2]
      group2:
        disable: False
        granularity: class
        classes: [test_module3.MyTestClass5, test_module3.MyTestClass6]
  suite_name_2:
    concurrency:
      max_workers: 2
    package: example
    groups:
      group1:
        disable: False
        granularity: class
        classes: [test_module3.MyTestClass7,
                  test_module3.MyTestClass8]

reporters:
  html:
    class: unishark.HtmlReporter
    kwargs:
      dest: logs
      overview_title: 'Example Report'
      overview_description: 'This is an example report'
      #uncomment the following to generate reports with customized templates
      #templates_path: mytemplates
      #report_template: myreport.html
      #overview_template: myoverview.html
      #index_template: myindex.html
  xunit:
    class: unishark.XUnitReporter
    kwargs:
      summary_title: 'Example Report'

test:
  suites: [suite_name_1, suite_name_2]
  concurrency:
    max_workers: 2
  reporters: [html, xunit]
  name_pattern: '^test\w*'