version: 1

suites:
  suite_name_1:
    max_workers: 6
    package: example
    groups:
      group1:
        disable: False
        granularity: module
        modules: [test_module1, test_module2]
      group2:
        disable: False
        granularity: class
        classes: [test_module3.MyTestClass5, test_module3.MyTestClass6]
  suite_name_2:
    max_workers: 2
    package: example
    groups:
      group1:
        disable: False
        granularity: class
        classes: [test_module3.MyTestClass7,
                  test_module3.MyTestClass8]

reporters:
  html:
    class: unishark.HtmlReporter
    kwargs:
      title: Example Report
      dest: logs
  xunit:
    class: unishark.XUnitReporter

test:
  suites: [suite_name_1, suite_name_2]
  max_workers: 2
  reporters: [html, xunit]