version: 1

suites:
  suite_name_1:
    package: example
    groups:
      group1:
        granularity: module
        modules: [test_module1, test_module2]
    concurrency:
      max_workers: 2
      level: module
  suite_name_2:
    package: example
    groups:
      group1:
        granularity: class
        classes: [test_module3.MyTestClass5, test_module3.MyTestClass6]
    concurrency:
      max_workers: 2
  suite_name_3:
    package: example
    groups:
      group1:
        granularity: class
        classes: [test_module3.MyTestClass7,
                  test_module3.MyTestClass8]
    concurrency:
      max_workers: 6
      level: method

reporters:
  html:
    class: unishark.HtmlReporter
    kwargs:
      dest: logs
      overview_title: 'Example Report'
      overview_description: 'This is an example report'
  xunit:
    class: unishark.XUnitReporter
    kwargs:
      summary_title: 'Example Report'

test:
  suites: [suite_name_1, suite_name_2, suite_name_3]
  concurrency:
    max_workers: 3
  reporters: [html, xunit]