version: 1

suites:
  suite_name_1:
    max_workers: 6
    package: example
    groups:
      group1:
        granularity: regex
        pattern: '^test_module[1-3]{1}\.[a-zA-Z]+[1-6]{1}\.\w+'
  suite_name_2:
    max_workers: 2
    package: example
    groups:
      group1:
        granularity: regex
        pattern: '^test_module3\.[a-zA-Z]+[7|8]{1}\.\w+'
reporters:
  html:
    class: unishark.HtmlReporter
    kwargs:
      dest: logs
      overview_title: 'Example Report'
  xunit:
    class: unishark.XUnitReporter
    kwargs:
      summary_title: 'Example Report'

test:
  suites: [suite_name_1, suite_name_2]
  max_workers: 2
  reporters: [html, xunit]