language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -r 3rdparty/python/requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install futures; fi
script:
  - scripts/run_tests.sh
